[program:exe]
command=/www/exe/exe serve
directory=/www/exe
user=livid
environment=HOME="/home/livid",USER="livid",EXE_HOME="/home/livid/.exe",PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

autostart=true
autorestart=unexpected
exitcodes=0
startsecs=5
startretries=3

stopsignal=TERM
stopwaitsecs=75
stopasgroup=true
killasgroup=true

redirect_stderr=true
stdout_logfile=/home/livid/.exe/supervisor.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
umask=0027
